language: csharp

solution: testcontainers-dotnet.sln

mono: none
dotnet: 2.1.502

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat='json%2copencover' /p:CoverletOutput=../bin/coverage/ /p:MergeWith='../bin/coverage/coverage.json'
    
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "test/bin/coverage/coverage.opencover.xml"
