image:
  - Visual Studio 2017

stack: docker

services:
  - docker

configuration: Release

install:
  - dotnet restore

build_script:
  - dotnet build

before_test:
  - docker info
  
test_script:
  - dotnet test
    
cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%USERPROFILE%\.local/share/NuGet/Cache'