image:
  - Visual Studio 2017

stack: docker

services:
  - docker

configuration: Release

install:
  - dotnet restore

build_script:
  - dotnet build

before_test:
  - docker info
  - docker pull mcr.microsoft.com/windows/nanoserver:sac2016
  
test_script:
  - dotnet test