image:
  - Visual Studio 2017

stack: docker

services:
  - docker

configuration: Release

install:
  - dotnet restore

build_script:
  - dotnet build

before_test:
  - docker info
  - docker pull alpine:3.5
  - docker image pull alpine:3.5
  
test_script:
  - dotnet test